### ISSUE TITLE
Incompatibility with Ubuntu 22.04LTS : catch2 submodule must be pulled to last 'devel' branch

### ISSUE THREAD

**Issue by blinard-BIOINFO** [phylo42/IPK#10]
v0.3.1.
See for instance : https://github.com/OpenImageDenoise/oidn/issues/106
I needed to updated catch2 to latest commits of devel branch so that test units can be run on Ubuntu 22.04 LTS.

**Comment by nromashchenko** [comment]
Tests on Ubuntu 22.04 LTS is now part of our CI/CD. As of today, IPK is compilable with no problems there. As I understand, this issue is outdated now because we updated catch (see [here](https://github.com/phylo42/I2L/tree/57ccc6f61d83a0c204cc34cadf9d90af9e5ae50b/tests)) after this issue was created.
